package com.codeforces.inmemo;

import com.codeforces.inmemo.dao.UserDao;
import com.codeforces.inmemo.dao.impl.UserDaoImpl;
import com.codeforces.inmemo.model.User;
import com.codeforces.inmemo.model.Wrapper;
import com.codeforces.inmemo.model.Wrapper.a;
import com.mchange.v2.c3p0.ComboPooledDataSource;
import org.apache.commons.lang3.RandomUtils;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.jacuzzi.core.Row;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import javax.sql.DataSource;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

import static org.hamcrest.core.Is.is;
import static org.hamcrest.core.IsNot.not;

/**
 * @author Mike Mirzayanov (mirzayanovmr@gmail.com)
 */
public class InmemoTest {
    private static final long USER_COUNT = 10000;
    private static final long BASE_SLEEP_MS = 1500;

    private UserDao userDao;
    private DataSource dataSource;

    private static DataSource newDataSource() {
        ComboPooledDataSource comboPooledDataSource = new ComboPooledDataSource();
        comboPooledDataSource.setJdbcUrl("jdbc:hsqldb:mem:inmemo");
        comboPooledDataSource.setUser("sa");
        comboPooledDataSource.setPassword("");
        return comboPooledDataSource;
    }

    @Before
    public void setup() throws SQLException {
        dataSource = newDataSource();

        userDao = new UserDaoImpl(dataSource);

        Connection connection = dataSource.getConnection();
        connection.createStatement().execute("DROP TABLE User IF EXISTS");
        connection.createStatement().execute("CREATE TABLE User (" +
                "ID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), " +
                "HANDLE VARCHAR(255), " +
                "OPENID VARCHAR(255), " +
                "EMAIL VARCHAR(255), " +
                "PASSWORD VARCHAR(255), " +
                "ADMIN BOOLEAN, " +
                "CREATIONTIME TIMESTAMP, " +
                "LASTONLINETIME TIMESTAMP, " +
                "DISABLED BOOLEAN," +
                "TSHIRTSIZE VARCHAR(255) " +
                ')'
        );

        for (int i = 0; i < USER_COUNT; i++) {
            userDao.insertRandom();
        }

        Inmemo.setDataSource(dataSource);
    }

    @Test
    public void testEnumField() throws InterruptedException {
        Inmemo.dropTableIfExists(User.class);

        // Create table.
        {
            Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
                add(Index.create("ID", Long.class, User::getId));
            }}.build(), true);
        }

        Map<Long, User> users = new HashMap<>();
        for (User.TShirtSize tShirtSize : User.TShirtSize.values()) {
            User user = userDao.newRandomUser();
            user.setTShirtSize(tShirtSize);
            userDao.insert(user);
            users.put(user.getId(), user);
        }

        Thread.sleep(BASE_SLEEP_MS);

        for (Map.Entry<Long, User> entry : users.entrySet()) {
            User inmemoUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", entry.getKey()));
            org.junit.Assert.assertEquals(entry.getValue().getTShirtSize(), inmemoUser.getTShirtSize());
        }
    }

    @Test
    public void testRowFilter() throws InterruptedException {
        Inmemo.dropTableIfExists(User.class);

        Inmemo.Filter<User> adminFilter = new Inmemo.Filter<User>() {
            @Override
            public boolean testRow(Row row) {
                return Boolean.TRUE.equals(row.get("ADMIN"));
            }

            @Override
            public boolean testItem(User user) {
                return user.isAdmin();
            }
        };
        Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
            add(Index.create("ID", Long.class, User::getId));
        }}.build(), adminFilter, true);
        int size = Inmemo.size(User.class);
        org.junit.Assert.assertTrue(size >= USER_COUNT * 0.45 && size <= USER_COUNT * 0.55);

        for (User user : userDao.findAll()) {
            Inmemo.insertOrUpdate(user);
        }
        org.junit.Assert.assertEquals(size, Inmemo.size(User.class));

        List<User> admins = new ArrayList<>();
        List<User> nonAdmins = new ArrayList<>();
        for (User user : userDao.findAll()) {
            if (user.isAdmin()) {
                admins.add(user);
            } else {
                nonAdmins.add(user);
            }
        }

        User randomAdmin = admins.get(RandomUtils.nextInt(0, admins.size()));
        randomAdmin.setHandle("???");
        userDao.update(randomAdmin);
        Inmemo.insertOrUpdateByIds(User.class, randomAdmin.getId());
        User inmemoRandomAdmin = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", randomAdmin.getId()));
        org.junit.Assert.assertEquals(randomAdmin.getHandle(), inmemoRandomAdmin.getHandle());

        User randomNonAdmin = nonAdmins.get(RandomUtils.nextInt(0, nonAdmins.size()));
        randomNonAdmin.setHandle("???");
        userDao.update(randomNonAdmin);
        Inmemo.insertOrUpdateByIds(User.class, randomNonAdmin.getId());
        User inmemoRandomNonAdmin = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", randomNonAdmin.getId()));
        org.junit.Assert.assertNull(inmemoRandomNonAdmin);
    }

    @Test
    public void testCommon() throws InterruptedException {
        Inmemo.dropTableIfExists(User.class);

        // Test user count.
        {
            Assert.assertEquals(USER_COUNT, userDao.findAll().size());
        }
        System.out.println(1);

        // Create table.
        {
            Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
                add(Index.create("ID", Long.class, User::getId));

                add(Index.create("handle", String.class, User::getHandle));

                add(Index.create("FIRST_HANDLE_LETTER", String.class, user -> user.getHandle().substring(0, 1)));
            }}.build(), true);
        }
        System.out.println(2);

        // Assert size.
        {
            Assert.assertEquals(USER_COUNT, Inmemo.size(User.class));
        }
        System.out.println(3);

        // Exactly one user with id=123.
        {
            List<User> users = Inmemo.find(User.class, new IndexConstraint<>("ID", 123L), user -> true);
            Assert.assertEquals(1, users.size());
            Assert.assertEquals(123L, users.get(0).getId());
        }
        System.out.println(4);

        // Tests that there is no user[id=USER_COUNT + 1], inserts it, waits, tests that the table contains it.
        {
            Assert.assertEquals(0, Inmemo.find(User.class, new IndexConstraint<>("ID", USER_COUNT + 1), user -> true).size());

            userDao.insertRandom();
            Thread.sleep(BASE_SLEEP_MS);

            List<User> users = Inmemo.find(User.class, new IndexConstraint<>("ID", USER_COUNT + 1), user -> true);
            Assert.assertEquals(1, users.size());
            Assert.assertEquals(USER_COUNT + 1, users.get(0).getId());
        }
        System.out.println(5);

        // Tests that there is no user[id=USER_COUNT + 2], inserts it, enforces update, tests that the table contains it.
        {
            Assert.assertEquals(0, Inmemo.find(User.class, new IndexConstraint<>("ID", USER_COUNT + 2), user -> true).size());

            userDao.insertRandom();
            Inmemo.update(User.class);

            List<User> users = Inmemo.find(User.class, new IndexConstraint<>("ID", USER_COUNT + 2), user -> true);
            Assert.assertEquals(1, users.size());
            Assert.assertEquals(USER_COUNT + 2, users.get(0).getId());
        }
        System.out.println(6);

        // Tests using second index that the number of users with first letter 'e' in handle is expected.
        {
            long eUsers1 = Inmemo.findCount(User.class, new IndexConstraint<>("FIRST_HANDLE_LETTER", "e"), user -> true);

            long eUsers2 = Inmemo.find(User.class, new IndexConstraint<>("FIRST_HANDLE_LETTER", "e"), user -> true).size();

            int expectedCount = userDao.findCountByHandlePrefix("e");
            Assert.assertEquals(expectedCount, eUsers1);
            Assert.assertEquals(expectedCount, eUsers2);
        }
        System.out.println(7);

        // Tests matcher.
        {
            long xyUsers = Inmemo.findCount(User.class, new IndexConstraint<>("FIRST_HANDLE_LETTER", "x"), user -> user.getHandle().charAt(1) == 'y');

            Assert.assertEquals(userDao.findCountByHandlePrefix("xy"), xyUsers);
        }
        System.out.println(8);

        // Tests that if we change user state in memory, it will no affect table unless we use insertOrUpdate.
        {
            User user13 = Inmemo.find(User.class, new IndexConstraint<>("ID", 13L), user -> true).get(0);

            user13.setHandle("handle13");

            org.junit.Assert.assertThat(user13.getHandle(), not(Inmemo.find(User.class, new IndexConstraint<>("ID", 13L), user -> true).get(0).getHandle()));

            Inmemo.insertOrUpdate(user13);

            org.junit.Assert.assertThat(user13.getHandle(), is(Inmemo.find(User.class, new IndexConstraint<>("ID", 13L), user -> true).get(0).getHandle()));
        }
        System.out.println(9);

        // Tests that findOnly throws exception if non-unique and throwOnNotUnique parameter is true;
        {
            boolean hasException = false;
            User existingUser = null;
            try {
                existingUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", USER_COUNT / 5));
            } catch (InmemoException e) {
                hasException = true;
            }
            Assert.assertFalse(hasException);

            User user = userDao.newRandomUser();
            user.setHandle(existingUser.getHandle());
            Inmemo.insertOrUpdate(user);

            List<User> possibleUsers = Arrays.asList(existingUser, user);

            hasException = false;
            try {
                User foundUser = Inmemo.findOnly(false, User.class, new IndexConstraint<>("handle", user.getHandle()));
                Assert.assertNotNull(foundUser);
                Assert.assertTrue(possibleUsers.contains(foundUser));
            } catch (InmemoException e) {
                hasException = e.getMessage().toLowerCase().contains("unique");
            }

            Assert.assertFalse(hasException);

            hasException = false;
            try {
                User foundUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("handle", user.getHandle()));
                Assert.assertNotNull(foundUser);
                Assert.assertTrue(possibleUsers.contains(foundUser));
            } catch (InmemoException e) {
                hasException = true;
            }

            Assert.assertTrue(hasException);
        }
        System.out.println(10);

        // Tests insertOrUpdateByIds method
        for (long i = 1; i <= USER_COUNT; i++) {
            User user = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", i));
            String newHandle = userDao.getRandomString();
            user.setHandle(newHandle);

            userDao.update(user);
            Inmemo.insertOrUpdateByIds(User.class, user.getId());

            User newUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", user.getId()));
            Assert.assertEquals(newHandle, newUser.getHandle());
        }
        System.out.println(11);
    }

    @Test
    public void testCompatibleClasses() throws InterruptedException {
        Inmemo.dropTableIfExists(Wrapper.a.class);

        // Test user count.
        {
            Assert.assertEquals(USER_COUNT, userDao.findAll().size());
        }

        // Create table.
        {
            Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
                add(Index.create("ID", Long.class, User::getId));
                add(Index.create("FIRST_HANDLE_LETTER", String.class, user -> user.getHandle().substring(0, 1)));
            }}.build(), true);
        }

//        Assert.assertEquals(1, Inmemo.findCount(User2.class, new IndexConstraint<Object>("ID", 11), new Matcher<User2>() {
//            @Override
//            public boolean match(User2 tableItem) {
//                return true;
//            }
//        }));

        Assert.assertEquals(1, Inmemo.findCount(Wrapper.a.class, new IndexConstraint<Object>("ID", 11L), user -> true));

        // Tests that there is no user[id=USER_COUNT + 1], inserts it, waits, tests that the table contains it.
        {
            List<a> users = Inmemo.find(a.class,
                    new IndexConstraint<>("ID", USER_COUNT + 1), user -> true);
            if (users.size() != 0) {
                System.out.println(users);
            }

            Assert.assertEquals(0, Inmemo.find(Wrapper.a.class,
                    new IndexConstraint<>("ID", USER_COUNT + 1), user -> true).size());

            userDao.insertRandom();
            Thread.sleep(BASE_SLEEP_MS);
            Assert.assertEquals(1, Inmemo.find(Wrapper.a.class,
                    new IndexConstraint<>("ID", USER_COUNT + 1), user -> true).size());
        }

        // Tests that there is no user[id=USER_COUNT + 2], inserts it, waits, tests that the table contains it.
        {
            Assert.assertEquals(0, Inmemo.find(Wrapper.a.class,
                    new IndexConstraint<>("ID", USER_COUNT + 2), user -> true).size());

            a x = new a();
            x.setId(USER_COUNT + 2);
            x.setHandle("aa");
            Inmemo.insertOrUpdate(x);

            Assert.assertEquals(1, Inmemo.find(Wrapper.a.class,
                    new IndexConstraint<>("ID", USER_COUNT + 2), user -> true).size());

            Assert.assertEquals(1,
                    Inmemo.find(User.class, new IndexConstraint<>("ID", USER_COUNT + 2), user -> user.getPassword() == null).size());
            Assert.assertEquals(0,
                    Inmemo.find(User.class, new IndexConstraint<>("ID", USER_COUNT + 2), user -> user.getPassword() != null).size());
        }
    }

    @Test
    public void testUnique() throws InterruptedException {
        Inmemo.dropTableIfExists(User.class);

        // Test user count.
        {
            Assert.assertEquals(USER_COUNT, userDao.findAll().size());
        }

        // Create table.
        {
            Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
                add(Index.createUnique("ID", Long.class, User::getId));
                add(Index.createUnique("handle", String.class, User::getHandle));
                add(Index.create("FIRST_HANDLE_LETTER", String.class, tableItem -> tableItem.getHandle().substring(0, 1)));
            }}.build(), true);
        }

        // Assert size.
        {
            Assert.assertEquals(USER_COUNT, Inmemo.size(User.class));
        }

        // Exactly one user with id=123.
        {
            Assert.assertEquals(1, Inmemo.find(User.class, new IndexConstraint<>("ID", 123L), user -> true).size());
        }

        // No one user with id=123 and false matcher.
        {
            Assert.assertEquals(0, Inmemo.find(User.class, new IndexConstraint<>("ID", 123L), user -> false).size());
        }

        // Exactly one user with id=123.
        {
            Assert.assertEquals(1, Inmemo.findCount(User.class, new IndexConstraint<>("ID", 123L)));
        }

        // Exactly one user with id=123.
        {
            Assert.assertEquals(123L, Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", 123L)).getId());
        }

        // Tests that there is no user[id=USER_COUNT + 1], inserts it, waits, tests that the table contains it.
        {
            Assert.assertNull(Inmemo.findOnly(false, User.class, new IndexConstraint<>("ID", USER_COUNT + 1)));

            userDao.insertRandom();
            Thread.sleep(BASE_SLEEP_MS);

            Assert.assertEquals(USER_COUNT + 1, Inmemo.findOnly(false, User.class, new IndexConstraint<>("ID", USER_COUNT + 1)).getId());
        }

        // Tests using second index that the number of users with first letter 'e' in handle is expected.
        {
            long id = USER_COUNT / 2;

            User userById = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", id));
            Assert.assertEquals(id, userById.getId());

            User userByHandle = Inmemo.findOnly(true, User.class, new IndexConstraint<>("handle", userById.getHandle()));

            Assert.assertNotNull(userByHandle);
            Assert.assertNotSame(userById, userByHandle);
            Assert.assertEquals(userById, userByHandle);

            List<User> usersByFirstHandleLetter = Inmemo.find(User.class, new IndexConstraint<>("FIRST_HANDLE_LETTER", userById.getHandle().substring(0, 1)));
            Assert.assertTrue(usersByFirstHandleLetter.contains(userById));
        }

        // Tests that if non-unique then throw exception.
        {
            User existingUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", USER_COUNT / 5));
            User user = userDao.newRandomUser();
            user.setHandle(existingUser.getHandle());

            boolean hasException = false;
            try {
                Inmemo.insertOrUpdate(user);
            } catch (InmemoException e) {
                hasException = e.getMessage().toLowerCase().contains("unique");
            }

            Assert.assertTrue(hasException);
        }

        // Tests matcher for unique indices
        {
            long id = USER_COUNT / 5;
            User existingUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", id));
            final String handle = existingUser.getHandle();
            User notFoundUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", id),
                    user -> !user.getHandle().equals(handle)
            );

            Assert.assertNull(notFoundUser);

            List<User> emptyUserList = Inmemo.find(User.class, new IndexConstraint<>("ID", id),
                    user -> !user.getHandle().equals(handle)
            );

            Assert.assertTrue(emptyUserList.isEmpty());
        }
    }

    @Test
    public void testEmergency() throws InterruptedException {
        Inmemo.dropTableIfExists(User.class);

        // Test user count.
        {
            Assert.assertEquals(USER_COUNT, userDao.findAll().size());
        }

        // Create table.
        {
            Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
                add(Index.createUnique("ID", Long.class, User::getId, indexValue -> new Object[]{"ID", indexValue}
                ));
                add(Index.createUnique("handle", String.class, User::getHandle));
                add(Index.createUnique("idAndHandle", String.class, user -> user.getId() + "," + user.getHandle(), indexValue -> {
                            String[] tokens = indexValue.split(",");
                            return new Object[]{"ID", Long.valueOf(tokens[0]), "HANDLE", tokens[1]};
                        }
                ));
                add(Index.create("FIRST_HANDLE_LETTER", String.class, tableItem -> tableItem.getHandle().substring(0, 1)));
            }}.build(), true);
        }

        // Assert size.
        {
            Assert.assertEquals(USER_COUNT, Inmemo.size(User.class));
        }

        Map<Thread, StackTraceElement[]> traces = Thread.getAllStackTraces();
        for (Thread thread : traces.keySet()) {
            if ("InmemoUpdater#class com.codeforces.inmemo.model.User".equals(thread.getName())) {
                thread.interrupt();
                try {
                    Thread.sleep(BASE_SLEEP_MS * 2);
                } catch (InterruptedException e) {
                    // No operations.
                }
            }
        }

        userDao.insertRandom();
        Assert.assertEquals(USER_COUNT + 1, userDao.findAll().size());
        Assert.assertEquals(USER_COUNT + 1, Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", USER_COUNT + 1)).getId());

        userDao.insertRandom();
        Assert.assertEquals(1, Inmemo.findCount(User.class, new IndexConstraint<>("ID", USER_COUNT + 1)));
        Assert.assertEquals(1, Inmemo.findCount(User.class, new IndexConstraint<>("ID", USER_COUNT + 2)));
        Assert.assertEquals(0, Inmemo.findCount(User.class, new IndexConstraint<>("ID", USER_COUNT + 3)));

        userDao.insertRandom();
        Assert.assertEquals(1, Inmemo.findCount(User.class, new IndexConstraint<>("ID", USER_COUNT + 3)));

        Assert.assertEquals(0, Inmemo.find(User.class, new IndexConstraint<>("ID", USER_COUNT + 4)).size());
        userDao.insertRandom();
        Assert.assertEquals(1, Inmemo.find(User.class, new IndexConstraint<>("ID", USER_COUNT + 4)).size());

        User newUser = userDao.newRandomUser();
        userDao.insert(newUser);
        User foundUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("idAndHandle", newUser.getId() + "," + newUser.getHandle()));
        newUser = userDao.find(newUser.getId());
        Assert.assertEquals(newUser, foundUser);
    }

    @Test
    public void testEmergencyDatabaseQuery() throws InterruptedException {
        Inmemo.dropTableIfExists(User.class);

        // Test user count.
        {
            Assert.assertEquals(USER_COUNT, userDao.findAll().size());
        }

        // Create table.
        {
            Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
                add(Index.createUnique("ID", Long.class, User::getId, id -> new Object[]{"id", id}
                        )
                );

                add(Index.create("handle", String.class, User::getHandle, handle -> new Object[]{"handle", handle}
                ));

                add(Index.create("handle2", String.class, User::getHandle));

                add(Index.create("FIRST_HANDLE_LETTER", String.class, tableItem -> tableItem.getHandle().substring(0, 1)));
            }}.build(), true);
        }

        // Assert size.
        {
            Assert.assertEquals(USER_COUNT, Inmemo.size(User.class));
        }

        {
            User newUser = userDao.newRandomUser();
            userDao.insert(newUser);

            List<User> foundUsers = Inmemo.find(User.class, new IndexConstraint<>("ID", newUser.getId()));
            newUser = userDao.find(newUser.getId());

            Assert.assertTrue(foundUsers.contains(newUser));
        }

        {
            User newUser = userDao.newRandomUser();
            userDao.insert(newUser);

            List<User> foundUsers = Inmemo.find(User.class, new IndexConstraint<>("handle", newUser.getHandle()));
            newUser = userDao.find(newUser.getId());

            Assert.assertTrue(foundUsers.contains(newUser));
        }

        {
            User newUser = userDao.newRandomUser();
            userDao.insert(newUser);

            List<User> foundUsers = Inmemo.find(User.class, new IndexConstraint<>("handle2", newUser.getHandle()));
            newUser = userDao.find(newUser.getId());

            Assert.assertFalse(foundUsers.contains(newUser));
        }

        {
            User newUser = userDao.newRandomUser();
            userDao.insert(newUser);
            List<User> foundUsers = Inmemo.find(User.class, new IndexConstraint<>("FIRST_HANDLE_LETTER",
                    newUser.getHandle().substring(0, 1)));
            newUser = userDao.find(newUser.getId());

            Assert.assertFalse(foundUsers.contains(newUser));

            Thread.sleep(BASE_SLEEP_MS * 2);

            foundUsers = Inmemo.find(User.class, new IndexConstraint<>("FIRST_HANDLE_LETTER",
                    newUser.getHandle().substring(0, 1)));
            Assert.assertTrue(foundUsers.contains(newUser));
        }
    }

    @Test
    public void testDeadlock() {
        // Test user count.
        {
            Assert.assertEquals(USER_COUNT, userDao.findAll().size());
        }

        Random random = new Random(123L);

        final List<Long> userIds = new ArrayList<>(100);
        for (int i = 0; i < 100; ++i)
            userIds.add((long) random.nextInt((int) USER_COUNT));

        // Create table.
        Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
            add(Index.createUnique("ID", Long.class, User::getId, id -> new Object[]{"id", id}
                    )
            );

            add(Index.create("handle", String.class, User::getHandle, handle -> new Object[]{"handle", handle}
            ));

            add(Index.create("handle2", String.class, User::getHandle));

            add(Index.create("FIRST_HANDLE_LETTER", String.class, tableItem -> tableItem.getHandle().substring(0, 1)));
        }}.build(), false);

        ExecutorService executorService = Executors.newFixedThreadPool(10);

        for (int i = 0; i < 10; ++i) {
            executorService.submit(() -> {
                for (Long userId : userIds) {
                    try {
                        User user = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", userId));
                        Assert.assertNotNull(user);
                    } catch (InmemoException e) {
                        Assert.assertTrue(e.getMessage().contains("Unable to find table for class name"));
                    }
                }
            });

            executorService.submit(() -> {
                for (Long userId : userIds) {
                    try {
                        Inmemo.insertOrUpdateByIds(User.class, userId);
                    } catch (InmemoException e) {
                        Assert.assertTrue(e.getMessage().contains("Unable to find table for class name"));
                    }
                }
            });
        }

        executorService.shutdown();

        try {
            Assert.assertTrue(executorService.awaitTermination(10, TimeUnit.SECONDS));
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    private void withTimestampLookback(boolean enabled, String indicator, Date floor, Consumer<Table<User>> check) {
        String property = "Inmemo.TimestampLookback." + User.class.getName();
        String oldLookback = System.getProperty(property);
        String oldJournal = System.getProperty("Inmemo.UseJournal");
        try {
            System.clearProperty(property);
            System.clearProperty("Inmemo.UseJournal");
            if (enabled) {
                System.setProperty(property, "true");
            }
            lookbackSql("DELETE FROM User");
            Table<User> table = new Table<>(User.class, indicator, null);
            table.add(Index.createUnique("ID", Long.class, User::getId));
            table.createUpdater(floor);
            check.accept(table);
        } finally {
            if (oldLookback == null) {
                System.clearProperty(property);
            } else {
                System.setProperty(property, oldLookback);
            }
            if (oldJournal == null) {
                System.clearProperty("Inmemo.UseJournal");
            } else {
                System.setProperty("Inmemo.UseJournal", oldJournal);
            }
        }
    }

    private void lookbackSql(String sql, Object... parameters) {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {
            for (int i = 0; i < parameters.length; i++) {
                if (parameters[i] instanceof Timestamp) {
                    statement.setTimestamp(i + 1, (Timestamp) parameters[i]);
                } else {
                    statement.setObject(i + 1, parameters[i]);
                }
            }
            statement.executeUpdate();
        } catch (SQLException e) {
            throw new AssertionError(e);
        }
    }

    private static Timestamp lookbackTime(int seconds) {
        return new Timestamp(Timestamp.valueOf("2026-01-01 12:00:00").getTime() + seconds * 1000L);
    }

    private void insertLookbackUser(long id, Timestamp time) {
        lookbackSql("INSERT INTO User (ID, HANDLE, CREATIONTIME, ADMIN, DISABLED) VALUES (?, ?, ?, FALSE, FALSE)",
                id, "u" + id, time);
    }

    private static User findLookbackUser(Table<User> table, long id) {
        return table.findOnly(true, new IndexConstraint<>("ID", id), user -> true);
    }

    private static void preloadLookbackTable(Table<User> table) {
        for (int i = 0; i < 4 && !table.isPreloaded(); i++) {
            table.getTableUpdaterForTesting().internalUpdate();
        }
        Assert.assertTrue(table.isPreloaded());
    }

    private static void makeLookbackDue(TableUpdater<?> updater) {
        updater.lastTimestampLookbackNanos = System.nanoTime() - TableUpdater.TIMESTAMP_LOOKBACK_INTERVAL_NANOS;
    }

    @Test
    public void testTimestampLookbackRecoversInsertAndEqualTimestampUpdates() {
        withTimestampLookback(true, "CREATIONTIME", null, table -> {
            insertLookbackUser(1, lookbackTime(14));
            insertLookbackUser(2, lookbackTime(20));
            preloadLookbackTable(table);
            TableUpdater<User> updater = table.getTableUpdaterForTesting();
            for (int i = 0; i < 10; i++) {
                updater.internalUpdate();
            }
            Map<Long, String> items = new HashMap<>();
            Map<Long, String> rows = new HashMap<>();
            table.add(new ItemListener<>("items", user -> items.put(user.getId(), user.getHandle())));
            table.add(new RowListener("rows", row -> rows.put((Long) row.get("ID"), (String) row.get("HANDLE"))));
            lookbackSql("UPDATE User SET HANDLE = 'changed'");
            insertLookbackUser(3, lookbackTime(14));
            updater.internalUpdate();
            Assert.assertEquals("u1", findLookbackUser(table, 1).getHandle());
            Assert.assertEquals("u2", findLookbackUser(table, 2).getHandle());
            Assert.assertNull(findLookbackUser(table, 3));
            Assert.assertTrue(items.isEmpty());
            makeLookbackDue(updater);
            updater.internalUpdate();
            for (long id : new long[]{1, 2, 3}) {
                String expected = id == 3 ? "u3" : "changed";
                Assert.assertEquals(expected, findLookbackUser(table, id).getHandle());
                Assert.assertEquals(expected, items.get(id));
                Assert.assertEquals(expected, rows.get(id));
            }
        });
    }

    @Test
    public void testTimestampLookbackPreservesAndAdvancesCursor() {
        withTimestampLookback(true, "CREATIONTIME", null, table -> {
            insertLookbackUser(1, lookbackTime(20));
            preloadLookbackTable(table);
            TableUpdater<User> updater = table.getTableUpdaterForTesting();
            lookbackSql("DELETE FROM User");
            insertLookbackUser(2, lookbackTime(14));
            makeLookbackDue(updater);
            updater.internalUpdate();
            Assert.assertNotNull(findLookbackUser(table, 2));
            insertLookbackUser(3, lookbackTime(18));
            updater.internalUpdate();
            Assert.assertNull(findLookbackUser(table, 3));
            insertLookbackUser(4, lookbackTime(30));
            makeLookbackDue(updater);
            updater.internalUpdate();
            Assert.assertNotNull(findLookbackUser(table, 3));
            Assert.assertNotNull(findLookbackUser(table, 4));
            lookbackSql("DELETE FROM User WHERE ID = 4");
            insertLookbackUser(5, lookbackTime(25));
            updater.internalUpdate();
            Assert.assertNull(findLookbackUser(table, 5));
            makeLookbackDue(updater);
            updater.internalUpdate();
            Assert.assertNotNull(findLookbackUser(table, 5));
        });
    }

    @Test
    public void testTimestampLookbackEligibility() {
        for (int mode = 0; mode < 3; mode++) {
            boolean enabled = mode != 0;
            String indicator = mode == 1 ? "ID" : "CREATIONTIME";
            withTimestampLookback(enabled, indicator, null, table -> {
                insertLookbackUser(20, lookbackTime(20));
                TableUpdater<User> updater = table.getTableUpdaterForTesting();
                makeLookbackDue(updater);
                long beforePreload = updater.lastTimestampLookbackNanos;
                preloadLookbackTable(table);
                Assert.assertEquals(beforePreload, updater.lastTimestampLookbackNanos);
                insertLookbackUser(14, lookbackTime(14));
                updater.lastTimestampLookbackNanos = System.nanoTime();
                updater.internalUpdate();
                Assert.assertNull(findLookbackUser(table, 14));
                System.setProperty("Inmemo.TimestampLookback." + User.class.getName(), String.valueOf(!enabled));
                makeLookbackDue(updater);
                long beforeDue = updater.lastTimestampLookbackNanos;
                updater.internalUpdate();
                if (enabled && "CREATIONTIME".equals(indicator)) {
                    Assert.assertNotNull(findLookbackUser(table, 14));
                    Assert.assertNotEquals(beforeDue, updater.lastTimestampLookbackNanos);
                } else {
                    Assert.assertNull(findLookbackUser(table, 14));
                    Assert.assertEquals(beforeDue, updater.lastTimestampLookbackNanos);
                }
            });
        }
    }

    @Test
    public void testTimestampLookbackWindowAndEmptyResult() {
        withTimestampLookback(true, "CREATIONTIME", null, table -> {
            insertLookbackUser(1, new Timestamp(lookbackTime(200).getTime() + 123));
            preloadLookbackTable(table);
            insertLookbackUser(2, new Timestamp(lookbackTime(80).getTime() + 123));
            insertLookbackUser(3, new Timestamp(lookbackTime(80).getTime() + 122));
            TableUpdater<User> updater = table.getTableUpdaterForTesting();
            makeLookbackDue(updater);
            updater.internalUpdate();
            Assert.assertNotNull(findLookbackUser(table, 2));
            Assert.assertNull(findLookbackUser(table, 3));
            lookbackSql("DELETE FROM User");
            makeLookbackDue(updater);
            updater.internalUpdate();
            Assert.assertTrue(table.isPreloaded());
        });
    }

    @Test
    public void testTimestampLookbackInitialFloorPrecision() throws SQLException {
        Timestamp floor;
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("VALUES (TIMESTAMP '2026-01-01 12:00:00.123456')");
             ResultSet result = statement.executeQuery()) {
            Assert.assertTrue(result.next());
            floor = result.getTimestamp(1);
        }
        Timestamp expectedFloor = (Timestamp) floor.clone();
        withTimestampLookback(true, "CREATIONTIME", floor, table -> {
            insertLookbackUser(1, lookbackTime(20));
            preloadLookbackTable(table);
            floor.setTime(lookbackTime(-60).getTime());
            insertLookbackUser(2, expectedFloor);
            insertLookbackUser(3, Timestamp.valueOf("2026-01-01 12:00:00.123455"));
            insertLookbackUser(4, Timestamp.valueOf("2026-01-01 12:00:00.122456"));
            TableUpdater<User> updater = table.getTableUpdaterForTesting();
            makeLookbackDue(updater);
            updater.internalUpdate();
            Assert.assertNotNull(findLookbackUser(table, 2));
            Assert.assertNull(findLookbackUser(table, 3));
            Assert.assertNull(findLookbackUser(table, 4));
        });
    }

    @Test
    public void testTimestampLookbackQueryAndListenerFailures() {
        withTimestampLookback(true, "CREATIONTIME", null, table -> {
            insertLookbackUser(20, lookbackTime(20));
            preloadLookbackTable(table);
            insertLookbackUser(14, lookbackTime(14));
            TableUpdater<User> updater = table.getTableUpdaterForTesting();
            makeLookbackDue(updater);
            long beforeFailure = updater.lastTimestampLookbackNanos;
            lookbackSql("ALTER TABLE User RENAME TO UserLookbackUnavailable");
            try {
                Assert.assertThrows(RuntimeException.class, updater::internalUpdate);
            } finally {
                lookbackSql("ALTER TABLE UserLookbackUnavailable RENAME TO User");
            }
            Assert.assertTrue(table.isPreloaded());
            Assert.assertNotEquals(beforeFailure, updater.lastTimestampLookbackNanos);
            updater.internalUpdate();
            Assert.assertNull(findLookbackUser(table, 14));
            makeLookbackDue(updater);
            updater.internalUpdate();
            Assert.assertNotNull(findLookbackUser(table, 14));

            for (int id = 15; id <= 17; id++) {
                insertLookbackUser(id, lookbackTime(id));
            }
            boolean[] failOnce = {true};
            table.add(new ItemListener<>("failure", user -> {
                if (user.getId() == 16 && failOnce[0]) {
                    failOnce[0] = false;
                    throw new IllegalStateException("Expected listener failure");
                }
            }));
            makeLookbackDue(updater);
            Assert.assertThrows(IllegalStateException.class, updater::internalUpdate);
            Assert.assertNotNull(findLookbackUser(table, 15));
            Assert.assertNull(findLookbackUser(table, 17));
            makeLookbackDue(updater);
            updater.internalUpdate();
            Assert.assertNotNull(findLookbackUser(table, 17));
            Assert.assertTrue(table.isPreloaded());
        });
    }

    @Test
    public void testTimestampLookbackBatchDiagnostics() {
        Logger logger = Logger.getLogger(TableUpdater.class);
        Level oldLevel = logger.getLevel();
        try {
            logger.setLevel(Level.DEBUG);
            for (int count : new int[]{11, 100}) {
                withTimestampLookback(true, "CREATIONTIME", null, table -> {
                    insertLookbackUser(1, lookbackTime(20));
                    preloadLookbackTable(table);
                    for (int id = 2; id <= count; id++) {
                        insertLookbackUser(id, lookbackTime(14));
                    }
                    TableUpdater<User> updater = table.getTableUpdaterForTesting();
                    makeLookbackDue(updater);
                    updater.internalUpdate();
                    Assert.assertEquals(count, table.size());
                });
            }
        } finally {
            logger.setLevel(oldLevel);
        }
    }

    @Test
    public void testJournal() throws IOException {
        System.setProperty("Inmemo.UseJournal", "true");

        File journalFile = new File("User.inmemo");
        journalFile.delete();

        try {
            Inmemo.dropTableIfExists(User.class);
            Assert.assertFalse(journalFile.isFile());

            // Create table.
            {
                Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
                    add(Index.create("ID", Long.class, User::getId));
                }}.build(), true);
            }

            Map<Long, User> users = new HashMap<>();
            for (long id = 1; id <= USER_COUNT; id++) {
                User inmemoUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", id));
                User dbUser = userDao.find(id);
                Assert.assertEquals(dbUser, inmemoUser);
                users.put(id, inmemoUser);
            }

            Inmemo.dropTableIfExists(User.class);
            Assert.assertTrue(journalFile.isFile());
            {
                Inmemo.createTable(User.class, "ID", null, new Indices.Builder<User>() {{
                    add(Index.create("ID", Long.class, User::getId));
                }}.build(), true);
            }

            for (long id = 1; id <= USER_COUNT; id++) {
                User inmemoUser = Inmemo.findOnly(true, User.class, new IndexConstraint<>("ID", id));
                User dbUser = userDao.find(id);
                Assert.assertEquals(dbUser, inmemoUser);
                Assert.assertEquals(users.get(id), inmemoUser);
            }
        } catch (Exception e) {
            System.err.println("Unexpected exception: " + e.getMessage());
            throw new RuntimeException("Unexpected exception: " + e.getMessage(), e);
        } finally {
            Assert.assertTrue(journalFile.isFile());
            Inmemo.deleteJournal(User.class);
            Assert.assertFalse(journalFile.isFile());
            System.setProperty("Inmemo.UseJournal", "false");
        }
    }
}
